modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "nootherfarms"
version = "${version}"
displayName = "No Other Farms"
authors = "orlouge"
description = ''''''
#logoFile = ""

[[dependencies.nootherfarms]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nootherfarms]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"